name: q_swipe
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flip_card: ^0.4.4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  shared_preferences: ^0.5.7
  photo_view: ^0.9.2
  flutter_launcher_icons: ^0.7.3
  url_launcher: ^5.4.5
  flutter_spinbox: ^0.1.0+1
  mailer: ^3.0.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/subjects/MAT.png
    - assets/subjects/SII.png
    - assets/subjects/PHY.png
    - assets/subjects/FRA.png
    - assets/subjects/ESP.png
    - assets/subjects/ENG.png
    - assets/icon/icon_fg.png
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: EBGaramond
      fonts:
        - asset: fonts/EB_Garamond/EBGaramond-Regular.ttf
        - asset: fonts/EB_Garamond/EBGaramond-Medium.ttf
        - asset: fonts/EB_Garamond/EBGaramond-MediumItalic.ttf
        - asset: fonts/EB_Garamond/EBGaramond-SemiBold.ttf
        - asset: fonts/EB_Garamond/EBGaramond-SemiBoldItalic.ttf
        - asset: fonts/EB_Garamond/EBGaramond-Bold.ttf
        - asset: fonts/EB_Garamond/EBGaramond-BoldItalic.ttf
        - asset: fonts/EB_Garamond/EBGaramond-ExtraBold.ttf
        - asset: fonts/EB_Garamond/EBGaramond-ExtraBoldItalic.ttf
        - asset: fonts/EB_Garamond/EBGaramond-Italic.ttf
          style: italic

    - family: LibreCaslonText
      fonts:
        - asset: fonts/Libre_Caslon_Text/LibreCaslonText-Regular.ttf
        - asset: fonts/Libre_Caslon_Text/LibreCaslonText-Bold.ttf
        - asset: fonts/Libre_Caslon_Text/LibreCaslonText-Italic.ttf
          style: italic

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-Black.ttf
        - asset: fonts/Montserrat/Montserrat-BlackItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
        - asset: fonts/Montserrat/Montserrat-BoldItalic.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraLight.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat/Montserrat-Light.ttf
        - asset: fonts/Montserrat/Montserrat-LightItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
        - asset: fonts/Montserrat/Montserrat-MediumItalic.ttf
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Thin.ttf
        - asset: fonts/Montserrat/Montserrat-ThinItalic.ttf

    - family: Oswald
      fonts:
        - asset: fonts/Oswald/Oswald-Bold.ttf
        - asset: fonts/Oswald/Oswald-Regular.ttf
        - asset: fonts/Oswald/Oswald-Medium.ttf
        - asset: fonts/Oswald/Oswald-Light.ttf
        - asset: fonts/Oswald/Oswald-ExtraLight.ttf
        - asset: fonts/Oswald/Oswald-SemiBold.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
